package injector

// Targets in a project generated by esb. Each pairs the marker comment the
// templates emit with the construct that marker sits in, so the generator
// still finds its place after a hand edit deleted or moved the marker, and
// the inspector reads the same construct the generator writes.
var (
	AppFields         = Target{Marker: "// esb:inject:app-fields", Find: StructFields("App")}
	AppServices       = Target{Marker: "// esb:inject:app-services", Find: BeforeFirstCall("NewApp", "handler")}
	AppInit           = Target{Marker: "// esb:inject:app-init", Find: BeforeReturn("NewApp")}
	AppReturnFields   = Target{Marker: "// esb:inject:app-return-fields", Find: CompositeLit("NewApp", "App")}
	ProjectionWorkers = Target{Marker: "// esb:inject:projection-workers", Find: VarLit("main", "workers")}
	AutomigrateModels = Target{Marker: "// esb:inject:automigrate-models", Find: CallArgs("NewProjectionDB", "AutoMigrate")}
	ApplyCases        = Target{Marker: "// esb:inject:apply-cases", Find: SwitchCases("Apply")}
	ApplyEventCases   = Target{Marker: "// esb:inject:applyevent-cases", Find: SwitchCases("applyEvent")}
	Routes            = Target{Marker: "// esb:inject:routes", Find: BlockEnd("RegisterRoutes")}
)
